export const CHAT_CONSTANTS = {
  HEADER_TITLE: "companion-chat",
  HEADER_SUBTITLE: "Private channel",
  INPUT_PLACEHOLDER: "Message #companion-chat",
  INTRO_MESSAGE: "Hello. I'm active and listening. What's on your mind?",
  ERROR_LOAD_HISTORY: "Unable to load chat history right now.",
  ERROR_OPEN_CONVERSATION: "Unable to open this conversation.",
  ERROR_EMPTY_RESPONSE: "Empty AI response.",
  ERROR_SEND_FAILED: "Message failed to send.",
  NO_HISTORY: "No history yet.",
  LOAD_OLDER_MESSAGES: "Load Older Messages",
  LOADING: "Loading...",
  WELCOME_TITLE: "Welcome to the Link.",
  WELCOME_SUBTITLE: "I am your digital twin. I'm ready to sync.",
  AI_NAME: "Digital Twin",
  USER_NAME: "You",
  TYPING: "typing...",
  NEW_CHAT_TOOLTIP: "New Chat",
  QUICK_PROMPTS: [
    "Reflect on this week",
    "I feel stressed",
    "Help me focus",
    "My energy is low",
  ],
};
